x = list(range(1,10,1))
print(x)
print("soma = " + str(sum(x)))
print("máximo = " + str(max(x)))
print("mínimo = " + str(min(x)))
count = x.count(5)
print("count = " + str(count))
x.sort(reverse=True)
print("Sort com verse = "+str(x))
